# FIle: oss.yml
# Author: aeternus <aeternus@aliyun.com>
# Date: 2019-11-18
# Description:
#   update changed files in Aliyun OSS bucket.
#   use `git diff` get changed files
#
# GIT_COMMIT_FILE:
#   file contains git commit id when prev updated

name: OSS

on:
  push:
    branches:
      - master

env:
  GIT_COMMIT_FILE: .git_commit

jobs:
  oss:
    name: OSS Update
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Download ossutil
        run: wget -O ossutil http://gosspublic.alicdn.com/ossutil/1.6.9/ossutil64 && chmod 755 ossutil

      - name: Config ossutil
        env:
          endpoint: ${{ secrets.OSS_endpoint }}
          accessKeyID: ${{ secrets.OSS_accessKeyID }}
          accessKeySecret: ${{ secrets.OSS_accessKeySecret }}
        run: ./ossutil config -e $endpoint -i $accessKeyID -k $accessKeySecret

      - name: Update changed files
        env:
          bucket: ${{ secrets.OSS_bucket }}
        run: |
          # Get prev GIT commit ID
          ./ossutil cp -f oss://$bucket/$GIT_COMMIT_FILE ./ || true
          if [ -f $GIT_COMMIT_FILE ]; then
              read GIT_COMMIT < $GIT_COMMIT_FILE
          fi
          
          # Update changed files
          while read -r status name1 name2; do
              case $status in
                  # files added or modified
                  A*|M*)
                      echo "OSS> UPLOAD: $name1"
                      ./ossutil cp -f "$name1" oss://$bucket/$name1
                      ;;

                  # files deleted
                  D*)
                      echo "OSS> DELETE: $name1"
                      ./ossutil rm -f oss://$bucket/$name1
                      ;;

                  # files renamed
                  R*)
                      echo "OSS> RENAME: $name1 --> $name2"
                      ./ossutil rm -f oss://$bucket/$name1
                      ./ossutil cp -f "$name2" oss://$bucket/$name2
                      ;;

                  # others, return error
                  *)
                      echo "GIT> UNKNOWN: $status:$name1:$name2"
                      exit -1
                      ;;
              esac
          done < <(git diff --name-status $GIT_COMMIT $GITHUB_SHA)

          # Update current git commit ID
          echo "OSS> UPLOAD: $GIT_COMMIT_FILE"
          echo $GITHUB_SHA > $GIT_COMMIT_FILE
          ./ossutil cp -f $GIT_COMMIT_FILE oss://$bucket/
